config:
  info: "this is a test config"
server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/185207048/springCloud-config.git
          search-paths:
            - springcloud-config
#          strict-host-key-checking: false
#          ignore-local-ssh-settings: true
#          private-key: ｜
#            -----BEGIN RSA PRIVATE KEY-----
#            MIIJKAIBAAKCAgEApBX06sK9ngRsiO1677tmELE/BbBDa5wUN+58fndtxW0L4ChS
#            KkxlHIxGoRpjZNr0uEIybJefP9oi9zq7ddfbYbyiZLKs9ODNfaIBVYdOEEoJqRnV
#            0ZGsRFlo1O9E9x+hyDk7qHV8Rlb2rpY21Kfn24CCGSQqmHe8laG16tBDZjDHG9c/
#            fjG+tGff7pQhq0E7Oxh7eHVQJKAK+1mmmZvMxSKZsnPwOENjAa7hnVeMdYLfd8ic
#            lmamrLz5Jm2jJ4Gxt2nZGRkDILIzbNIE0syIAvb0cjpu1R3uiQk/vIxl5bd5BqAT
#            Y7tXLpxR7sANv4LOtds9Y1khhkXm5U+fMBWBJd09E/uu69L6CG71pM/Sz57t3fVp
#            Z8PR5LCLOcgxsJDEaY/PyNWszKfNbqSTgbhws72yGgvJo+D5L+TUKfSRrkHl2Nbp
#            AnE+JNsNN1NDjGH+JVCuq688aJZvOWdGavXUBI6v/qkAgh4Sjz9+MlOdg9+GqwyZ
#            7qeoGykRN+XWBcqxjPq7TOggTpVOtgilpiPZ/M4STLuEjdkGHOImekAujFPuYu5k
#            O1doB0G6FRCJ78ipp81b3TQ0wDgXmxX/u/h5sd8Znzwz4Xf3QL3rUMi5dBRAOdhL
#            iVXwijqkLFjsHQdiuvRtG/CD1jBudxoVlT5wvZT3w8EDV6noUTG6FQgfRVkCAwEA
#            AQKCAgEAkqwlz6vf/14I/qT5XU3wQD+QDC+xNIHB+PUvR4TOFMoS8X5ZZAIB5/Dk
#            OaHy8vZeBk717+fgrBz7YG+Zng8jxUvvBYBJ5mMEjKbB9ogKGbl0xTmYzcofaMFb
#            Weu/g/88iFPQphbOzblyrEEOJi0oridDI+IWSU/OvRpeGNWtSa2UbaiM0ur4gx7P
#            Jt428nRO09ZgmB6VUwfUiTVsHKcN9bGmHcRRGJnz6E9A0XquzWP9CX/DqRV9K6+I
#            LveV/fyKtV7idvLKvvFL0pwxP5UghzXk8C6XX91vmgMwfAQsGZlVj7yLWHzfw4Rs
#            ILSAFY6B5EFjsGi99N6LNLNlon+2fom7beq9PnM+WSEeeLV0qbBRQvUUGPo9elON
#            7A+mUv6YpLsWo+3LCKXEMIdr5ICCSjgX/KRjBw84B3OtGPZrHahaGdD6CwSfXHah
#            2aWqpenArCErppXUFrOYmzixjCgjOfNZuoFJUON2hxNUrLCOPiJP1aZpCQzhxjYv
#            JVUTIX2QdS+uS+KtFlZhuy+sIDR0H61Qhrc6BFiRsrxmLwVgq3hIkVdgJK8gzCys
#            mnZ5VbwKb9NfEEVKaCbHuxOuIftd0UwenHQLGv9suNmxD5jv49iplb7hc+y8uUo4
#            Zm25VwZgpsnMh9OtrYiH1qcYdUiquIkGVs5kyqCMHncN8XfZS+ECggEBANCDF7A1
#            n0CL/s13H/ZNM4REEI4kaEgskfCt3/RcqXN22tZJ8UvuCHvSFHZPDU/j8sbQtM42
#            lzO/EQP26ft0X/SZ5Vidsd0GAl6S4Izti5vIQ70IjWk12680LMDAbUJh7T/jnvv4
#            Q2J4vdr/2mOW1ZIwoNpQr+p3mM8M9c8yrkkKTbLxw8JWLpucJqf1uQCuShouEzjS
#            7RFLs0IzyZ0rwAbMNM8F3QgDiqSsp1QQlMMdaIGdhsaOSR8NERNP8BWzOrTPIVYX
#            gtku7vCGmr4uWS14jpmH94C53XGhsz713YfPorYgQNKjdjlJg4Ua0dVKaiMBp6Gy
#            9BPz/0op5sx4gb0CggEBAMl0q8hBwH7mxM566zqiLyg9rPfbitJO+rv7qZko26Nk
#            UbH7qO9ixu4byOG/c5OL7dVRgexWr3/qKktAoxghygI0Yz7cWC4FqnYfY/chIyV/
#            t1rknkV9UHxcw6qwYDEuLEotJHMzf3u0wrpGz2gOPOQSsv0gi7hlfFADJD2iJpYW
#            Xx6FD4TkiojN2Q66QeTuumD3cYsC0s4DD8LH+w8OBDBPKEIhILSy5TS9D3jLEpRZ
#            HFrKKguukc09m1ybKbynGpe0vXYRQbTVntV4LYzmqSQF17qqAIFVhJPdH+tIfu8E
#            rpFDHw9GNyhwprXoFaOwf5CyGwSUmW9hypRrPBzkdc0CggEAK72UVo6pHa1AgnGe
#            7tg7Gl/86RSSG7Hd25NeC7D0ixg/x/wy9i608OSdDkR/EmdLIpHdm/Svu1c1hpNh
#            ejJrfrBaAED0ct0z2gsNuAKM6t0T+K+2mn+F2jcjvDuhr+9DCcgCLfFikWGq0ioh
#            8gpOOyCgXavXe2QjVivt1M1Y6lGTAxrcagQSOuqC4XEWoiHtwZgwyBbXTG2I6TZb
#            8PCgk8x6t4MPXwL/LpRZdbUUv+mHZslY4IYwqKbhEiAOyT6T7iIVaC3+cPj7ftF9
#            3K90XamQoHx5WzOiVJgLNgX1tuvDwlj5wDYyMspNILsDka7OnRFXzP/xW84vm6s2
#            k2YkMQKCAQANjlZI4XPMlkbEBi1yApvdv1i2TQWoZTwmDic5cTBmbEe7DE4v3Zu5
#            RhFcb3+dfBsC8bsmZiblGqLB8ZWH+C4Zu+C5yCX+4s63qCEX7hjpWxDBgwTLdEVI
#            OQ3JnJi8dnjwfN0pC1wWvPEli8JFJEAgsMlukxQT0nBtCekUZKboDpVT/mwu6xoP
#            XpqujQYGG7Ja+Auh6Qy6ZCZZWw+f0beicJEq8gO7ZRZbWCWEYVXcuapYyaXOp26U
#            OwMLVj2Wvj/h2X2uRjb/rihEARQ/mP3kuKftnabvDQwgzw5ozLYN62i7yaJ7aqQn
#            in0NXJKoMyZCXFnJEx7ICfKRzi17XDw5AoIBAH4s6QfJypDowRXJiJHgrXB7Q4VM
#            QTe2+QYHNyyo2+qORtgVn4le5xr4bAtmdCYPCDUN+PMtd//C3yQHAoUqeOBDgqlh
#            Av43JB2mOdW8bRR/v+EhB22ZUiPeZzxn6vINwv204ySzRpqajxV0noNFd8SpAdyv
#            zXVB+0YCU9tLw4+SW8RNELf/DSuxfSA2A7V2yGyZNrkZlFw1YEhbCn721FVDMhZL
#            HlKDj1/aMQLqI607w+ERNOytWsjGgfLHsTwMfs9CjsIUmxXAdBU7WXiH0mVG0Yy7
#            Ct2nb3ckZcedll1uqNg8mzFIKlFto0cH2TgQi91Ln8Qn9hF+XCUFrfV+5r4=
#            -----END RSA PRIVATE KEY-----
      label: master

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka
